# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primera_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFileButton.setGeometry(QtCore.QRect(90, 39, 170, 71))
        self.selectFileButton.setAcceptDrops(True)
        self.selectFileButton.setObjectName("selectFileButton")
        self.fileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLineEdit.setGeometry(QtCore.QRect(280, 70, 400, 25))
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(180, 140, 70, 30))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(520, 110, 161, 81))
        self.confirmButton.setObjectName("confirmButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 50, 181, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 150, 71, 16))
        self.label_2.setObjectName("label_2")
        self.selectVinPort = QtWidgets.QSpinBox(self.centralwidget)
        self.selectVinPort.setGeometry(QtCore.QRect(390, 120, 45, 30))
        self.selectVinPort.setObjectName("selectVinPort")
        self.selectVoutPort = QtWidgets.QSpinBox(self.centralwidget)
        self.selectVoutPort.setGeometry(QtCore.QRect(390, 160, 45, 30))
        self.selectVoutPort.setObjectName("selectVoutPort")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 130, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(330, 170, 51, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectFileButton.setText(_translate("MainWindow", "Select or drop .csv file"))
        self.confirmButton.setText(_translate("MainWindow", "Confirm"))
        self.label.setText(_translate("MainWindow", "Selected file"))
        self.label_2.setText(_translate("MainWindow", "Select offset"))
        self.label_3.setText(_translate("MainWindow", "Vin Port"))
        self.label_4.setText(_translate("MainWindow", "Vout Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
