# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primera_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 279)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectFileButton.setGeometry(QtCore.QRect(90, 39, 170, 71))
        self.selectFileButton.setAcceptDrops(True)
        self.selectFileButton.setObjectName("selectFileButton")
        self.fileLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.fileLineEdit.setGeometry(QtCore.QRect(280, 70, 400, 25))
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(180, 140, 70, 30))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(520, 110, 161, 81))
        self.confirmButton.setObjectName("confirmButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 50, 181, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 150, 71, 16))
        self.label_2.setObjectName("label_2")
        self.selectV1Port = QtWidgets.QSpinBox(self.centralwidget)
        self.selectV1Port.setGeometry(QtCore.QRect(340, 120, 45, 30))
        self.selectV1Port.setObjectName("selectV1Port")
        self.selectV2Port = QtWidgets.QSpinBox(self.centralwidget)
        self.selectV2Port.setGeometry(QtCore.QRect(340, 160, 45, 30))
        self.selectV2Port.setObjectName("selectV2Port")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 130, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 170, 41, 16))
        self.label_4.setObjectName("label_4")
        self.selectV3Port = QtWidgets.QSpinBox(self.centralwidget)
        self.selectV3Port.setGeometry(QtCore.QRect(460, 120, 45, 30))
        self.selectV3Port.setObjectName("selectV3Port")
        self.selectV4Port = QtWidgets.QSpinBox(self.centralwidget)
        self.selectV4Port.setGeometry(QtCore.QRect(460, 160, 45, 30))
        self.selectV4Port.setObjectName("selectV4Port")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 130, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 170, 41, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 772, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectFileButton.setText(_translate("MainWindow", "Select or drop .csv file"))
        self.confirmButton.setText(_translate("MainWindow", "Confirm"))
        self.label.setText(_translate("MainWindow", "Selected file"))
        self.label_2.setText(_translate("MainWindow", "Select offset"))
        self.label_3.setText(_translate("MainWindow", "V1 Port"))
        self.label_4.setText(_translate("MainWindow", "V2 Port"))
        self.label_5.setText(_translate("MainWindow", "V3 Port"))
        self.label_6.setText(_translate("MainWindow", "V4 Port"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
